apiVersion: triggers.tekton.dev/v1alpha1
kind: EventListener
metadata:
  name: api-webhook
spec:
  serviceAccountName: tekton-triggers-sa
  triggers:
    - name: deploy-trigger-for-backend
      bindings:
      - ref: backend-triggerbinding
      template:
        ref: backend-triggertemplate
      interceptors:
      - github:
          eventTypes: ["push"]
      - cel:
          filter: "body.repository.name == 'watson-speech-to-text-backend' && body.ref.split('/')[2] == 'master'"
