apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nishiki-watson-speech-to-text-backend
commonAnnotations:
  enzo: "true"
resources:
- deployment.yaml
- service.yaml
- route.yaml
