apiVersion: route.openshift.io/v1
kind: Route
metadata:
  # annotations:
  #   argocd.argoproj.io/sync-options: Validate=false
  #   openshift.io/host.generated: "true"
  name: backend
  labels:
    app: watson-speech-to-text-backend
  annotations:
    haproxy.router.openshift.io/timeout: 60s #default timeout 30s
spec:
  tls:
    termination: edge
  to:
     kind: Service
     name: watson-speech-to-text-backend
     weight: 100
  wildcardPolicy: None
